version: '3.1'

services:
  db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_USER=samarkand
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
