# Elixir CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.7
        environment:
          MIX_ENV: test

      - image: circleci/postgres:9
        environment:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: bazaar

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install hex deps
          command: |
            mix local.hex --force
            mix local.rebar --force
      - restore_cache:
          keys:
            - mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - mix-cache-{{ .Branch }}
            - mix-cache-
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}
            - build-cache-
      - run: mix do deps.get, compile
      - run: mix ecto.create
      - run: mix test
      - save_cache:
          key: mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: build-cache-{{ .Branch }}
          paths: "_build"
