# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.4
        environment:
          MIX_ENV: test
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: secret

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          name: Install hex deps
          command: |
            mix local.hex --force
            mix local.rebar --force
      - restore_cache:
          keys:
            - mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - mix-cache-{{ .Branch }}
            - mix-cache
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}
            - build-cache
      - run: mix do deps.get, compile
      - run: mix ecto.create
      - run: mix test
      - save_cache:
          key: mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: mix-cache
          paths: "deps"
      - save_cache:
          key: build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: build-cache
          paths: "_build"
